language: python

cache:
  directories:
  - $HOME/gnatsd

python:
  - 2.6.9
  - 2.7

env:
  - DEBUG_NATS_TEST=true

before_install:
  - bash ./script/install_gnatsd.sh

before_script:
  - export PATH=$HOME/gnatsd:$PATH
  
script:
  - ./script/test.sh

notifications:
  email: false

sudo: false

